FROM node:erbium-alpine

RUN mkdir -p /usr/app
WORKDIR /usr/app

ENV PATH /usr/app/node_modules/.bin:$PATH

COPY package*.json /usr/app/
RUN npm i --silent

COPY . /usr/app

EXPOSE 3000

CMD npm run serve